[package]
name = "centauro_server"
version = "0.3.0"
authors = ["Toni Bergas", "Jan-Bernat Roselló"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4"

